[profile.default]
remappings = ['forge-std/=lib/forge-std/src/', 'solmate/=lib/solmate/src/', 'chainlink/=lib/chainlink/contracts/src/v0.8/', 'libddrv/=lib/libddrv/src/']

[profile.ci.fuzz]
runs = 10_000
